# Generated by Django 5.1.2 on 2024-10-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="due_date",
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
