# Generated by Django 5.1.2 on 2024-10-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_template_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateitem",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
